name: Publish Stream Deck Plugin

on:
  push:
    tags:
      - 'v*' # Only run on tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Build project
      run: yarn build

    - name: Install Stream Deck CLI
      run: yarn global add @elgato/cli

    - name: Pack Stream Deck Plugin
      run: streamdeck pack net.aosankaku.cpu-partyparrot.sdPlugin

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: net.aosankaku.cpu-partyparrot.streamDeckPlugin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}